server:
  port: 8082

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  #缓存管理器
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml #缓存加载配置文件
  #使用Thymeleaf模板引擎
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false  #使用Thymeleaf模板引擎，关闭缓存
    servlet:
      content-type: text/html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_alibaba?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  mail:
    host: smtp.163.com
    username: cytus2019@163.com
    password: IRNIWMABONCAXVRE
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#MyBatis配置
mybatis:
  type-aliases-package: com.czy.entity #别名定义
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #指定 MyBatis 所用日志的具体实现，未指定时将自动查找
    map-underscore-to-camel-case: true #开启自动驼峰命名规则（camel case）映射
    lazy-loading-enabled: true #开启延时加载开关
    aggressive-lazy-loading: false #将积极加载改为消极加载（即按需加载）,默认值就是false
    #lazy-load-trigger-methods: "" #阻挡不相干的操作触发，实现懒加载
    cache-enabled: true #打开全局缓存开关（二级环境），默认值就是true

# 自定义配置
com:
  czy:
    name: spring-boot-demo
    password: ENC(0XEZz/020e6q8xT1Bk71qA==)

# 打印RequestMapping中的所有接口信息，生产环境不建议开启
logging:
  level:
    root: info
    org.mybatis: debug
    java.sql: debug
    org.springframework.web: trace

# 敏感信息加解密配置
jasypt:
  encryptor:
    #加解密的密码
    password: key-czy
    #jasypt默认更改了算法，如果不指定那么会报错：failed to bind properties under 'spring.datasource.druid.password' to java.lang.String
    #解决办法：①把版本降到2.x②指定加密方法，如下
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
